[package]
name = "flat_map"
version = "0.0.1"
authors = ["Jason Toffaletti <toffaletti@gmail.com>"]
description = "A compact map using a shorted vector of (key, value)"
license = "Apache-2.0"
repository = "https://github.com/toffaletti/flat_map.git"
readme = "README.md"

[lib]
name = "flat_map"
doctest = false
